### ISSUE TITLE
GKE AutoPilot: No NET_BROADCAST

### ISSUE THREAD

**Issue by kylekurz** [1Password/connect#21]
Tried to test a deployment to GKE in autopilot mode tonight and got an error deploying the helm chart that one of the containers was requesting `NET_BROADCAST`, which is not available in autopilot. Is this a functional requirement that means I need to move back to traditional GKE setup, or is this something that can be configured?

**Comment by rootssoftware** [comment]
Hi @kylekurz,

We were encountering the same kind of issues deploying One Password Connect and the One Password Connect Operator to a clients Kubernetes cluster (private cloud via a Belgian provider) using the Helm Chart. We were able to work around the issue by just following the installation instructions using Helm and then manually patching the onepassword-connect deployment so it uses an additional serviceaccount we specifically created for it. We then coupled this servcieaccount via a clusterrolebinding to a podSecurityPolicy that allows the pods to run priviliged without limitations. So far our proof of concept is working and onepassword-connect and onepassword-connect-operator are functioning flawlessly. If it is an option for you, you could try and solve it that way too. :)

In the same way, you could also try and create a podSecurityPolicy that specifically allows the NET_BROADCAST capability, along with other specific requirements for the deployment to work. We were successfull to some extend this way, be ran into additional issues because the initcontainer of the onepassword-connect deployment wants to run as root and our clients cluster enforces a default policy that all pods must run unprivileged (non root).

To conclude: I do think we both encountered a limitation of the helm chart and the way the onepassword-connect deployment is set up, rather than a limitation of our environment.

Disclaimer: We do not recommend running your pods privileged, especially in a production environment.

**Comment by jpcoenen** [comment]
Hi @kylekurz,

Thank you for reaching out! I understand your concerns about using `NET_BROADCAST`. This capability is currently used for an auto-discovery mechanism between the two Connect containers. 

We may have some options to replace this auto-discovery with static peer configuration to avoid requesting the `NET_BROADCAST` capability. I am going to take back to my team and see what we can do.

**Comment by jpcoenen** [comment]
One approach that came up in a team conversation is setting a static port for the shared bus and add a `$OP_BUS_PEERS` configuration parameter to specify which peers to connect to. Setting `$OP_BUS_PEERS` disables auto-discovery and therefore the need for `NET_BROADCAST`.

For the api container that would like something like this:
```
OP_BUS_PORT=10200
OP_BUS_PEERS=connect-sync:10200
```

And for the sync container:
```
OP_BUS_PORT=10200
OP_BUS_PEERS=connect-api:10200
```

In case you have multiple api containers, `$OP_BUS_PEERS` for the sync container can be a comma-separated list of multiple peers:
```
OP_BUS_PORT=10200
OP_BUS_PEERS=connect-api-1:10200,connect-api-2:10200
```

----

Would such an approach work for your use-case?

**Comment by kylekurz** [comment]
@jpcoenen that seems reasonable, but I admit I'm so early in this process that I'm not sure I'll be the best at vetting these solutions. I am happy to try some things for you if you can help me with getting the "right" chart, as I'm still in a sandbox, but would need to request some patience with me while I struggle through some of it. :)

**Comment by jpcoenen** [comment]
This change is in progress now. I will make sure it also makes it into the Helm Chart, which means most extra set up will be taken care of.

**Comment by jpcoenen** [comment]
We have just released a [new version](https://github.com/1Password/connect-helm-charts/releases/tag/connect-1.7.0) of the Helm chart. This version should no longer ask for the `NET_BROADCAST` capability.

**Comment by kylekurz** [comment]
Trying this out now, will let you know if I have more questions. Thanks so much for your quick turnaround!

**Comment by kylekurz** [comment]
Can confirm this worked for both enabling GKE AutoPilot _and_ utilizing the fix for https://github.com/1Password/connect-helm-charts/issues/67. Thank you!

**Comment by jpcoenen** [comment]
Thank you for confirming. I am glad to hear it is working now 😃
